/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package williansalceda;

/**
 *
 * @author WillianSalceda
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInsertSomeValue = new javax.swing.JLabel();
        txtNumberInserted = new javax.swing.JSpinner();
        btnCalculate = new javax.swing.JButton();
        lblDivision = new javax.swing.JLabel();
        lblRemainder = new javax.swing.JLabel();
        lblSquareRoot = new javax.swing.JLabel();
        lblCubicRoot = new javax.swing.JLabel();
        lblAbsoluteValue = new javax.swing.JLabel();
        txtDivision = new javax.swing.JLabel();
        txtRemainder = new javax.swing.JLabel();
        txtSquareRoot = new javax.swing.JLabel();
        txtCubicRoot = new javax.swing.JLabel();
        txtAbsolutValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblInsertSomeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInsertSomeValue.setText("Insert some value:");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDivision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDivision.setText("Division (/):");

        lblRemainder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRemainder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRemainder.setText("Remainder (%): ");

        lblSquareRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSquareRoot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSquareRoot.setText("Square Root:");

        lblCubicRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCubicRoot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCubicRoot.setText("Cubic Root:");

        lblAbsoluteValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAbsoluteValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAbsoluteValue.setText("Absolut Value:");

        txtDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDivision.setForeground(new java.awt.Color(255, 0, 51));
        txtDivision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDivision.setText("0");

        txtRemainder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRemainder.setForeground(new java.awt.Color(255, 0, 51));
        txtRemainder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRemainder.setText("0");

        txtSquareRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSquareRoot.setForeground(new java.awt.Color(255, 0, 51));
        txtSquareRoot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSquareRoot.setText("0");

        txtCubicRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCubicRoot.setForeground(new java.awt.Color(255, 0, 51));
        txtCubicRoot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCubicRoot.setText("0");

        txtAbsolutValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAbsolutValue.setForeground(new java.awt.Color(255, 0, 51));
        txtAbsolutValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtAbsolutValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblInsertSomeValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumberInserted, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCubicRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAbsoluteValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCubicRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAbsolutValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertSomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberInserted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDivision)
                        .addGap(18, 18, 18)
                        .addComponent(lblRemainder)
                        .addGap(18, 18, 18)
                        .addComponent(lblSquareRoot)
                        .addGap(18, 18, 18)
                        .addComponent(lblCubicRoot)
                        .addGap(18, 18, 18)
                        .addComponent(lblAbsoluteValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDivision)
                        .addGap(18, 18, 18)
                        .addComponent(txtRemainder)
                        .addGap(18, 18, 18)
                        .addComponent(txtSquareRoot)
                        .addGap(18, 18, 18)
                        .addComponent(txtCubicRoot)
                        .addGap(18, 18, 18)
                        .addComponent(txtAbsolutValue)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        lblDivision.setVisible(true);
        lblRemainder.setVisible(true);
        lblSquareRoot.setVisible(true);
        lblCubicRoot.setVisible(true);
        lblAbsoluteValue.setVisible(true);
        
        txtDivision.setVisible(true);
        txtRemainder.setVisible(true);
        txtSquareRoot.setVisible(true);
        txtCubicRoot.setVisible(true);
        txtAbsolutValue.setVisible(true);
        
        int num = Integer.parseInt(txtNumberInserted.getValue().toString());
        int division = num / 2;
        int remainder = num % 2;
        double squareRoot = Math.sqrt(num);
        double cubicRoot = Math.cbrt(num);
        int absoluteValue = Math.abs(num);
        
        txtDivision.setText(Integer.toString(division));
        txtRemainder.setText(Integer.toString(remainder));
        txtSquareRoot.setText(Double.toString(squareRoot));
        txtCubicRoot.setText(Double.toString(cubicRoot));
        txtAbsolutValue.setText(Integer.toString(absoluteValue));
        
        
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblDivision.setVisible(false);
        lblRemainder.setVisible(false);
        lblSquareRoot.setVisible(false);
        lblCubicRoot.setVisible(false);
        lblAbsoluteValue.setVisible(false);
        
        txtDivision.setVisible(false);
        txtRemainder.setVisible(false);
        txtSquareRoot.setVisible(false);
        txtCubicRoot.setVisible(false);
        txtAbsolutValue.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblAbsoluteValue;
    private javax.swing.JLabel lblCubicRoot;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblInsertSomeValue;
    private javax.swing.JLabel lblRemainder;
    private javax.swing.JLabel lblSquareRoot;
    private javax.swing.JLabel txtAbsolutValue;
    private javax.swing.JLabel txtCubicRoot;
    private javax.swing.JLabel txtDivision;
    private javax.swing.JSpinner txtNumberInserted;
    private javax.swing.JLabel txtRemainder;
    private javax.swing.JLabel txtSquareRoot;
    // End of variables declaration//GEN-END:variables
}
